version: '3.8'

services:
  dbd-bot:
    build: .
    container_name: dbd-discord-bot
    restart: unless-stopped
    
    # Environment variables
    environment:
      - NODE_ENV=production
    
    # Mount .env file
    env_file:
      - .env
    
    # Volumes for persistent data
    volumes:
      - ./src/data:/app/src/data
      - ./logs:/app/logs
    
    # Resource limits
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
    
    # Health check
    healthcheck:
      test: ["CMD", "node", "-e", "console.log('Bot is running')"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    
    # Logging
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Optional: Monitoring with Watchtower
  watchtower:
    image: containrrr/watchtower
    container_name: watchtower
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_CLEANUP=true
      - WATCHTOWER_POLL_INTERVAL=3600
    command: dbd-discord-bot
